name: emi_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  collection: ^1.17.0
  csv: ^6.0.0
  currency_picker: ^2.0.21
  device_info_plus: ^11.1.1
  file_picker: ^8.1.4
  fl_chart: ^0.69.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.3.1
  onboarding: ^4.0.2
  open_file: ^3.5.9
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  riverpod_annotation: ^2.3.4
  share_plus: ^10.1.2
  showcaseview: ^3.0.0
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
